#!/usr/bin/env python3
'''\
Usage: fixup-coverage COVERAGE
Make sure we skip lines we should do in the coverage JSON files; COVERAGE
should be the JSON result of OutputJsonCoverage from the profiling package.
'''
import json, re, sys

SKIP_PATTERN = '^[ \t]*$|^\s*(local|InstallGlobalFunction|InstallMethod|#)'
SKIP_RE = re.compile(SKIP_PATTERN)

def fixup(cov):
    for filename, lines in cov['coverage'].items():
        with open(filename, encoding = 'latin1') as handle:
            for index, line in enumerate(handle):
                if re.match(SKIP_RE, line):
                    cov['coverage'][filename][str(index + 1)] = None
    return cov

if __name__ == '__main__':
    if len(sys.argv) < 1:
        print(__doc__, file = sys.stderr)
        sys.exit(1)

    json_file = sys.argv[1]
    try:
        with open(json_file) as handle:
            cov = json.load(handle)
    except IOError:
        print('could not open "%s" for reading' % json_file, file = sys.stderr)
        sys.exit(1)

    result = fixup(cov)

    try:
        with open(json_file, 'w') as handle:
            json.dump(result, handle)
    except IOError:
        print('could not open "%s" for writing' % json_file, file = sys.stderr)
        sys.exit(1)

