#!/bin/bash
# pickgroups COUNT FILENAME
# Pick some random groups.
if [ "$#" -lt 2 ]; then
	echo "Usage: $0 COUNT FILENAME" >&2
	echo "Pick COUNT groups, saving the resulting list to the file FILENAME." >&2
	exit 1
fi

count=$1
filename=$2

script="$(mktemp newss.XXXXXXX.g)"
cat > "$script" <<EOF
LoadPackage("newss");;
ReadPackage("newss", "test/tests.g");;
SetInfoLevel(NewssGroupSelInfo, 2);
SaveGroupsList(PickManyGroups(DefaultGroupSource, false, $count), "$filename");
QUIT_GAP(true);
EOF

${GAP:-gap} --quitonbreak -q -o 4G "$script"
result=$?
rm $script
exit $result
