codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

fixes:
    - "./gap/**::"

ignore:
    - "**/init.g"
    - "**/read.g"
    - "**/PackageInfo.g"
    # I'm not too interested in the coverage for the test suite, especially
    # since we don't expect 100% coverage (e.g. load/save code in some runs,
    # the failure cases, etc.)
    - "**/test/*.g"
