sudo: false
dist: trusty
language: c
compiler:
    - gcc

env:
    global:
        - GAP="./gap/gap -l /tmp/gaproot;./gap"
        - testdir=.
    matrix:
        - HPCGAP=yes
        - HPCGAP=no

install: ./test/travis-setup
script: ./test/runtests 50 && ./test/runtests --coverage ./test/groups.grp test AllTests
after_script: curl -s https://codecov.io/bash | bash -s -- -f ./test.cov.json -e HPCGAP
