#!/bin/bash
testdir=../tests
profile=no
if [ "$1" == "--profile" ]; then
	profile=yes
	shift
fi
count=${1:-100}
if [ -z "$2" ]; then
	filename=tests-$(git rev-parse --short HEAD)-$(date "+%s").csv
else
	filename="$2"
fi

gap <<EOF
LoadPackage("newss");;
ReadPackage("newss", "lib/tests.g");;
RESULTS_FILENAME := "$testdir/$filename";;
PickSomeGroups($count);
$(if [ "$profile" == "yes" ]; then cat <<EOP
Print("Profiling...");
NUM_RANDOM_TEST_ELTS := 2^14;
ProfileLineByLine("$testdir/prof-$filename.gz");
EOP
fi) 
DoAllTests();
$(if [ "$profile" == "yes" ]; then cat <<EOP
UnprofileLineByLine();
LoadPackage("profiling");
OutputAnnotatedCodeCoverageFiles("$testdir/prof-$filename.gz", "$testdir/prof-$filename");
EOP
fi)
EOF

